server:
  port: 3344

spring:
  application:
    name: cloud-config-server #服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pl1111w/config.git
          search-paths: prod,sit  #读取文件夹
      label: mater   #读取分支
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
       defaultZone: http://localhost:7001/eureka