server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer #服务名称
  cloud:
    stream:
      binders:
        defaultRabbit:   #表示配置要绑定的rabbit的服务消息
          type: rabbit   #消息组件类型
          environment:  #设置消息组件环境
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          destination:  studyExchange  #使用的exchange定义
          content-type: application/json
          binder: defaultRabbit
          group: groupA #同组竞争关系，不同组重复消费
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#    集群版eureka
#       defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka
#    单机版eureka
       defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: recieve-8802.com
    prefer-ip-address: true  #访问路径变为ip地址
#    #默认向注册中心发送心跳的时间30s(默认)
    lease-expiration-duration-in-seconds: 2
#    #注册中心等待发送心跳的时间90s(默认)
    lease-renewal-interval-in-seconds: 5
