server:
  port: 80

spring:
  application:
    name: cloud-consumer-hystrix-order #服务名称

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#    集群版eureka
#       defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka
#    单机版eureka
       defaultZone: http://localhost:7001/eureka/
#feign开启hystrix
feign:
   hystrix:
     enabled: true