server:
  port: 80

spring:
  application:
    name: cloud-concumer-feignOrder #服务名称
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
       defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka
# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
    ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
    ConnectTimeout: 5000
logging:
  level:
      # feign日志以什么级别监控哪个接口
    com.pl1111w.springcloud.service.PaymentFeignService: debug