server:
  port: 80

spring:
  application:
    name: cloud-concumer-order #服务名称
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
       defaultZone: http://localhost:7001/eureka/